name: Publish Documentation
on:
  push:
    branches:
      - "5.x"
      - "5.x-*"
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  install-mdbook:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        continue-on-error: true
        id: cache-mdbook
        with:
          key: mdbook
          path: ./cargo/**/*
      - if: ${{ steps.cache-mdbook.outputs.cache-hit != 'true' }}
        name: Install mdbook
        env:
          CARGO_HOME: ./cargo
        run: cargo install mdbook-admonish@v10.0.2 mdbook-variables@v0.2.2 mdbook mdbook-toc mdbook-pagetoc

  install-tfdocs:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        id: cache-tfdocs
        with:
          key: tfdocs
          path: ./tfdocs/terraform-docs
      - if: ${{ steps.cache-tfdocs.outputs.cache-hit != 'true' }}
        name: Install terraform-docs
        run: |
          go install github.com/terraform-docs/terraform-docs@v0.16.0
          mkdir ./tfdocs; mv `go env GOPATH`/bin/terraform-docs ./tfdocs/

  build-and-deploy:
    needs: [install-mdbook, install-tfdocs]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        continue-on-error: true
        with:
          key: mdbook
          path: ./cargo/**/*
      - uses: actions/cache@v3
        with:
          key: tfdocs
          path: ./tfdocs/terraform-docs

      - name: Generate docs
        shell: bash
        env:
          CARGO_HOME: ./cargo
        run: |
          export PATH=`pwd`/tfdocs:`pwd`/cargo/bin:${PATH}
          make mdbuild
          touch ./docs/book/.nojekyll

      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/book'
      - uses: actions/deploy-pages@v2
        id: deployment
