name: Publish Terraform OCI OKE Module Book
on:
  push:
    tags:
      - 'v5.*'
    branches:
      - 'docs/**'
      - 'main'
      - '5.x'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: $GITHUB_REF_NAME
    - name: Install mdbook
      run: |
        # Download mdbook
        mkdir ./mdbook
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz \
          | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH

        # Create and switch to separate worktree
        git worktree add -b $GITHUB_REF_NAME docs || exit 1 && pushd docs
        git config user.name "GitHub Actions"
        git config user.email "oci-dax-tools_ww@oracle.com"

        # Build the tfdocs and HTML content
        make mdbuild || exit 1   # Generate docs
        touch .nojekyll          # Don't run published files through Jekyll
        git add .                # Stage new content
        git commit -m "Deploy $GITHUB_SHA to $GITHUB_REF_NAME-docs"
        git pull --rebase \      # Rebase on latest and push; suffix on conflict
          && git push $GITHUB_REF_NAME:$GITHUB_REF_NAME-docs \
              || git push --force-with-lease "$GITHUB_REF_NAME:$GITHUB_REF_NAME-docfail"
        pop; git worktree remove --force $GITHUB_REF_NAME # Exit and remove workspace

